edition = "2021"
hard_tabs = true
merge_derives = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Off"

# May need nightly rustfmt
wrap_comments = true
comment_width = 80
